packages:
  - packages/*

catalog:
  '@eslint/eslintrc': 3.2.0
  '@eslint/js': 9.18.0
  '@faker-js/faker': 10.1.0
  '@keyv/redis': 5.1.4
  '@nestjs/cache-manager': 3.0.1
  '@nestjs/cli': 11.0.0
  '@nestjs/common': 11.0.1
  '@nestjs/config': 4.0.2
  '@nestjs/core': 11.0.1
  '@nestjs/mapped-types': '*'
  '@nestjs/platform-express': 11.0.1
  '@nestjs/schematics': 11.0.0
  '@nestjs/swagger': 11.2.3
  '@nestjs/testing': 11.0.1
  '@nestjs/typeorm': 11.0.0
  '@swc/cli': 0.6.0
  '@swc/core': 1.15.3
  '@testcontainers/postgresql': 11.9.0
  '@testcontainers/redis': 11.9.0
  '@types/express': 5.0.5
  '@types/node': 24.10.1
  '@types/supertest': 6.0.2
  '@vitest/coverage-v8': 4.0.14
  cache-manager: 7.2.4
  class-transformer: 0.5.1
  class-validator: 0.14.2
  dotenv: 17.2.3
  eslint: 9.18.0
  eslint-config-prettier: 10.0.1
  eslint-plugin-prettier: 5.2.2
  firebase-admin: 13.6.0
  globals: 16.0.0
  joi: 18.0.1
  keyv: 5.5.5
  nuxt: ^4.2.1
  pg: 8.16.3
  pg-mem: 3.0.5
  prettier: 3.4.2
  reflect-metadata: 0.2.2
  rxjs: 7.8.1
  source-map-support: 0.5.21
  supertest: 7.0.0
  ts-loader: 9.5.2
  ts-node: 10.9.2
  tsconfig-paths: 4.2.0
  turbo: 2.6.3
  typeorm: 0.3.27
  typescript: 5.7.3
  typescript-eslint: 8.20.0
  unplugin-swc: 1.5.9
  vitest: 4.0.14
  vue: ^3.5.25
  vue-router: ^4.6.3
  yaml: 2.8.1

cleanupUnusedCatalogs: true

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@scarf/scarf'
  - protobufjs
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build
