packages:
  - packages/*

catalog:
  '@eslint/eslintrc': 3.2.0
  '@eslint/js': 9.18.0
  '@faker-js/faker': 10.1.0
  '@hey-api/openapi-ts': 0.88.0
  '@keyv/redis': 5.1.4
  '@nestjs/cache-manager': 3.0.1
  '@nestjs/cli': 11.0.0
  '@nestjs/common': 11.0.1
  '@nestjs/config': 4.0.2
  '@nestjs/core': 11.0.1
  '@nestjs/mapped-types': '*'
  '@nestjs/platform-express': 11.0.1
  '@nestjs/schematics': 11.0.0
  '@nestjs/swagger': 11.2.3
  '@nestjs/testing': 11.0.1
  '@nestjs/typeorm': 11.0.0
  '@radix-ui/react-avatar': 1.1.11
  '@radix-ui/react-collapsible': 1.1.12
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-separator': 1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-tooltip': 1.2.8
  '@swc/cli': 0.6.0
  '@swc/core': 1.15.3
  '@tailwindcss/postcss': '4'
  '@types/express': 5.0.5
  '@types/node': 24.10.1
  '@types/react': '19'
  '@types/react-dom': '19'
  '@types/supertest': 6.0.2
  '@vitest/coverage-v8': 4.0.14
  babel-plugin-react-compiler: 1.0.0
  baseline-browser-mapping: 2.8.32
  cache-manager: 7.2.4
  class-transformer: 0.5.1
  class-validator: 0.14.2
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dotenv: 17.2.3
  eslint-config-next: 16.0.3
  eslint-config-prettier: 10.0.1
  eslint-plugin-prettier: 5.2.2
  firebase: 12.6.0
  firebase-admin: 13.6.0
  globals: 16.0.0
  joi: 18.0.1
  lucide-react: 0.554.0
  next: 16.0.3
  pg: 8.16.3
  pg-mem: 3.0.5
  prettier: 3.4.2
  react: 19.2.0
  react-dom: 19.2.0
  reflect-metadata: 0.2.2
  rxjs: 7.8.1
  source-map-support: 0.5.21
  supertest: 7.0.0
  tailwind-merge: 3.4.0
  tailwindcss: '4'
  ts-loader: 9.5.2
  ts-node: 10.9.2
  tsconfig-paths: 4.2.0
  tw-animate-css: 1.4.0
  typeorm: 0.3.27
  typescript-eslint: 8.20.0
  unplugin-swc: 1.5.9
  vitest: 4.0.14
  yaml: 2.8.1

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@scarf/scarf'
  - protobufjs
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build

injectWorkspacePackages: true