packages:
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@scarf/scarf'
  - protobufjs
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build
